### ISSUE TITLE
CustomError: Cannot find package '@grpc/grpc-js' imported from C:\wechat-openai-qa-bot-main\node_modules\wechaty-token\dist\esm\src\grpc-js.js

### ISSUE THREAD

**Issue by TTTsuperpyer** [choogoo/wechat-openai-qa-bot#20]
PS C:\wechat-openai-qa-bot-main> npm start

> openai-qa-bot@1.6.5 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node index.ts

C:\wechat-openai-qa-bot-main\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:757
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
CustomError: Cannot find package '@grpc/grpc-js' imported from C:\wechat-openai-qa-bot-main\node_modules\wechaty-token\dist\esm\src\grpc-js.js
    at packageResolve (C:\wechat-openai-qa-bot-main\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:757:9)
    at moduleResolve (C:\wechat-openai-qa-bot-main\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (C:\wechat-openai-qa-bot-main\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:912:11)
    at C:\wechat-openai-qa-bot-main\node_modules\ts-node\src\esm.ts:218:35
    at entrypointFallback (C:\wechat-openai-qa-bot-main\node_modules\ts-node\src\esm.ts:168:34)
    at C:\wechat-openai-qa-bot-main\node_modules\ts-node\src\esm.ts:217:14
    at addShortCircuitFlag (C:\wechat-openai-qa-bot-main\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (C:\wechat-openai-qa-bot-main\node_modules\ts-node\src\esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
PS C:\wechat-openai-qa-bot-main>

![image](https://user-images.githubusercontent.com/63111979/206134871-70152cd8-843f-4478-9d2c-9e5fab38b348.png)

**Comment by choogoo** [comment]
It seems that the dependent package was not installed successfully, you can try to uninstall all dependencies and reinstall
