### ISSUE TITLE
这是什么原因，请帮我分析一下可以吗？

### ISSUE THREAD

**Issue by 254317693** [choogoo/wechat-openai-qa-bot#21]
file:///C:/Users/25431/wechat-openai-qa-bot/index.ts:224
      chatdev.pub_event(eventMessage('onMessage', { curDate }))
                                                            ^
TypeError: chatdev.pub_event is not a function
    at WechatyImpl.onMessage (file:///C:/Users/25431/wechat-openai-qa-bot/index.ts:224:61)
    at WechatyImpl.emit (node:events:539:35)
    at WechatyImpl.emit (node:domain:475:12)
    at WechatyImpl.emit (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetXp.<anonymous> (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

**Comment by 254317693** [comment]
> openai-qa-bot@1.9.2 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node index.ts

================================================

主程序载入系统配置成功，等待插件初始化...

================================================
12:38:23 INFO Starter Bot Started.
12:38:27 WARN Room findAll() message.ready() rejection: Error: not logged in, no this.__currentUserId yet.
12:38:27 ERR {"code":2,"details":"GError: message not found for id: clcr68rgf0000lkb6773w9v6u\n    at Function.from (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/gerror/src/gerror/gerror.ts:69:17)\n    at PuppetXp.<anonymous> (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45)","message":"message not found for id: clcr68rgf0000lkb6773w9v6u","name":"GError","stack":"GError: message not found for id: clcr68rgf0000lkb6773w9v6u\n    at Function.from (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/gerror/src/gerror/gerror.ts:69:17)\n    at PuppetXp.<anonymous> (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45)"}
12:38:27 ERR {}
12:38:32 WARN Room findAll() message.ready() rejection: Error: not logged in, no this.__currentUserId yet.
12:38:32 ERR {"code":2,"details":"GError: message not found for id: clcr68vsu0001lkb6bvsl2bnc\n    at Function.from (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/gerror/src/gerror/gerror.ts:69:17)\n    at PuppetXp.<anonymous> (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45)","message":"message not found for id: clcr68vsu0001lkb6bvsl2bnc","name":"GError","stack":"GError: message not found for id: clcr68vsu0001lkb6bvsl2bnc\n    at Function.from (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/gerror/src/gerror/gerror.ts:69:17)\n    at PuppetXp.<anonymous> (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:277:45)"}
12:38:32 ERR {}
12:39:00 INFO StarterBot [object Object] login
12:39:00 INFO onMessage {"_events":{},"_eventsCount":0,"id":"clcr69h960002lkb6ht3304cy","payload":{"id":"clcr69h960002lkb6ht3304cy","listenerId":"","roomId":"49462858011@chatroom","talkerId":"wxid_qv76ehp73hne22","text":"目前SHA256被认为无法破解","timestamp":1673411940762,"toId":"","type":7}}
onMessage {"_events":{},"_eventsCount":0,"id":"clcr69h960002lkb6ht3304cy","payload":{"id":"clcr69h960002lkb6ht3304cy","listenerId":"","roomId":"49462858011@chatroom","talkerId":"wxid_qv76ehp73hne22","text":"目前SHA256被认为无法破解","timestamp":1673411940762,"toId":"","type":7}}
12:39:00 INFO onMessage {"_events":{},"_eventsCount":0,"id":"clcr69h970003lkb6exos4g76","payload":{"id":"clcr69h970003lkb6exos4g76","listenerId":"","roomId":"49462858011@chatroom","talkerId":"wxid_qv76ehp73hne22","text":"是因为没有破解方法","timestamp":1673411940763,"toId":"","type":7}}
onMessage {"_events":{},"_eventsCount":0,"id":"clcr69h970003lkb6exos4g76","payload":{"id":"clcr69h970003lkb6exos4g76","listenerId":"","roomId":"49462858011@chatroom","talkerId":"wxid_qv76ehp73hne22","text":"是因为没有破解方法","timestamp":1673411940763,"toId":"","type":7}}
12:39:00 INFO 最新消息池长度： 1
12:39:00 INFO 最新消息池长度： 2
file:///C:/Users/25431/wechat-openai-qa-bot/index.ts:224
      chatdev.pub_event(eventMessage('onMessage', { curDate }))
                                                            ^
TypeError: chatdev.pub_event is not a function
    at WechatyImpl.onMessage (file:///C:/Users/25431/wechat-openai-qa-bot/index.ts:224:61)
    at WechatyImpl.emit (node:events:539:35)
    at WechatyImpl.emit (node:domain:475:12)
    at WechatyImpl.emit (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetXp.<anonymous> (file:///C:/Users/25431/wechat-openai-qa-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)
可以正常启用，但获取wx列表后接收2条信息就挂了。 @atorber @choogoo

**Comment by atorber** [comment]
It seems that you have turned on the mqtt push switch, but have not configured the mqtt information correctly.
